-- Target DBMS : Oracle 19c
--

-- 
-- TABLE: AUTHORS 
--

CREATE TABLE AUTHORS(
    AUTHOR_ID     NUMBER(10, 0)    NOT NULL,
    FIRST_NAME    VARCHAR2(100)    NOT NULL,
    LAST_NAME     VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK_AUTHORS PRIMARY KEY (AUTHOR_ID)
)
;



-- 
-- TABLE: BOOKS 
--

CREATE TABLE BOOKS(
    BOOK_ID             NUMBER(14, 0)    NOT NULL,
    TITLE               VARCHAR2(256)    NOT NULL,
    AUTHOR_ID           NUMBER(10, 0)    NOT NULL,
    BORROWER_ID         NUMBER(10, 0)    NOT NULL,
    ISBN_TEN            NUMBER(10, 0),
    ISBN_THIRTEEN       NUMBER(13, 0),
    NUM_OF_PAGES        NUMBER(10, 0),
    ON_LOAN             VARCHAR2(1)      DEFAULT 'N' NOT NULL
                        CHECK (ON_LOAN in ('Y','N')),
    PUBLICATION_DATE    DATE,
    PUBLISHER           VARCHAR2(200),
    CONSTRAINT PK_BOOKS_BKID PRIMARY KEY (BOOK_ID)
)
;



-- 
-- TABLE: BORROWERS 
--

CREATE TABLE BORROWERS(
    BORROWER_ID           NUMBER(10, 0)    NOT NULL,
    FIRST_NAME            VARCHAR2(100)    NOT NULL,
    LAST_NAME             VARCHAR2(100)    NOT NULL,
    STREET_ADDRESS        VARCHAR2(200),
    CITY_NAME             VARCHAR2(100),
    STATE_OF_RESIDENCE    VARCHAR2(2),
    POSTAL_CODE           VARCHAR2(9),
    STATUS                VARCHAR2(10)     DEFAULT 'INACTIVE' NOT NULL
                          CHECK (STATUS in ('ACTIVE','INACTIVE','DISABLED')),
    CONSTRAINT PK_BORROWERS PRIMARY KEY (BORROWER_ID)
)
;



-- 
-- INDEX: I_AUTHORS_LNFN 
--

CREATE INDEX I_AUTHORS_LNFN ON AUTHORS(LAST_NAME, FIRST_NAME)
;
-- 
-- INDEX: I_BOOKS_TTLAUTHID 
--

CREATE INDEX I_BOOKS_TTLAUTHID ON BOOKS(TITLE, AUTHOR_ID)
;
-- 
-- INDEX: I_BOOKS_ATHRID 
--

CREATE INDEX I_BOOKS_ATHRID ON BOOKS(AUTHOR_ID)
;
-- 
-- INDEX: I_BOOKS_ISBN10 
--

CREATE INDEX I_BOOKS_ISBN10 ON BOOKS(ISBN_TEN)
;
-- 
-- INDEX: I_BOOKS_ISBN13 
--

CREATE INDEX I_BOOKS_ISBN13 ON BOOKS(ISBN_THIRTEEN)
;
-- 
-- INDEX: I_BOOKS_BRWRID 
--

CREATE INDEX I_BOOKS_BRWRID ON BOOKS(BORROWER_ID)
;
-- 
-- INDEX: I_BORROWERS_LNFN 
--

CREATE INDEX I_BORROWERS_LNFN ON BORROWERS(LAST_NAME, FIRST_NAME)
;
-- 
-- INDEX: I_BORROWERS_STCTYSTRT 
--

CREATE INDEX I_BORROWERS_STCTYSTRT ON BORROWERS(STATE_OF_RESIDENCE, CITY_NAME, STREET_ADDRESS)
;
-- 
-- FOREIGN KEYS: BOOKS 
--

ALTER TABLE BOOKS ADD CONSTRAINT FK_P_AUTHORS_C_BOOKS 
    FOREIGN KEY (AUTHOR_ID)
    REFERENCES AUTHORS(AUTHOR_ID)
;

ALTER TABLE BOOKS ADD CONSTRAINT FK_P_BORROWERS_C_BOOKS 
    FOREIGN KEY (BORROWER_ID)
    REFERENCES BORROWERS(BORROWER_ID)
;

